# Generated by Django 4.2.5 on 2025-02-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variable', models.CharField(choices=[('2m_temperature', '2m_temperature'), ('surface_pressure', 'surface_pressure'), ('sea_surface_temperature', 'sea_surface_temperature'), ('total_precipitation', 'total_precipitation')], max_length=50)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('max_lat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('min_lat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('max_lon', models.DecimalField(decimal_places=20, max_digits=25)),
                ('min_lon', models.DecimalField(decimal_places=20, max_digits=25)),
                ('temporalResolution', models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('month', 'month'), ('year', 'year')], max_length=10)),
                ('spatialResolution', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
